server:
  port: 8050

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka
    proxy-host:

spring:
  application:
    name: api-gateway
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,gateway