server:
  port: 8050

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-discovery-service-service:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tweet-service-service
          uri: lb://tweet-service-service
          predicates:
            - Path=/api/tweets/{segment}
            - Method=GET, POST, DELETE, PUT, OPTIONS
        - id: user-service-service
          uri: lb://user-service-service
          predicates:
            - Path=/api/user/{segment}
            - Method=GET, POST, DELETE, PUT, OPTIONS
        - id: timeline-service-service
          uri: lb://timeline-service-service
          predicates:
            - Path=/api/timeline/{segment}
        - id: auth-service-service
          uri: lb://auth-service-service
          predicates:
            - Path=/api/auth/{segment}
            - Method=GET, POST, DELETE, PUT, OPTIONS
        - id: follow-service-service
          uri: lb://follow-service-service
          predicates:
            - Path=/api/follow/{segment}
        - id: trending-service-service
          uri: lb://trending-service-service
          predicates:
            - Path=/api/trending/{segment}
        - id: like-service-service
          uri: lb://like-service-service
          predicates:
            - Path=/api/like/{segment}
management:
  endpoints:
    web:
      exposure:
        include: health,gateway