server:
  port: 8050

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-discovery-service:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tweet-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/tweets/**
        - id: account-service
          uri: http://localhost:8069
          predicates:
            - Path=/api/account/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"