server:
  port: 8050

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: tweet-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/tweets/{segment}
            - Method=GET, POST, DELETE, PUT, OPTIONS
        - id: user-service
          uri: http://localhost:8069
          predicates:
            - Path=/api/user/{segment}
            - Method=GET, POST, DELETE, PUT, OPTIONS
        - id: timeline-service
          uri: http://localhost:8068
          predicates:
            - Path=/api/timeline/{segment}
        - id: auth-service
          uri: http://localhost:8067
          predicates:
            - Path=/api/auth/{segment}
        - id: follow-service
          uri: http://localhost:8066
          predicates:
            - Path=/api/follow/{segment}
management:
  endpoints:
    web:
      exposure:
        include: health,gateway