server:
  port: 8050

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8040/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tweet-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/tweets/**
        - id: account-service
          uri: http://localhost:8069
          predicates:
            - Path=/api/account/**